spring:
  application:
    name: orphelins
  profiles:
    active: prod
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    enabled: false

# Configuration Swagger/OpenAPI
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  show-actuator: false
  packages-to-scan: com.gestion.orphelins.controller

server:
  port: 8080
  error:
    include-stacktrace: never

# Configuration JWT
jwt:
  secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
  expiration: 7200000
  issuer: gestion-orphlins-api

# Configuration Logging
logging:
  level:
    org.springframework.data.mongodb: DEBUG
